### ISSUE TITLE
Codepen examples not working on Firefox 38

### ISSUE THREAD

**Issue by hamoid** [SciutoAlex/p5d3-connect#2]
For some reason the loading of the d3 library is blocked (JavaScript security issues probably). No idea why it works in Chromium then.

**Comment by SciutoAlex** [comment]
Is this when you're viewing the CodePen examples?

**Comment by hamoid** [comment]
Yes, I copy the URL from the example and try to watch it in the browser. Works on Chromium, but not in Firefox (at least on my computer).
![2015-06-21-183650_846x113_scrot](https://cloud.githubusercontent.com/assets/108264/8272493/923f271e-1844-11e5-9983-92ea2d8ebf8e.png)

**Comment by SciutoAlex** [comment]
I can reproduce your error if I try to access Codepen over https. But if it's http, it works. Could that be the problem?

**Comment by SciutoAlex** [comment]
Well here's the fix. In CodePen I was using:
http://d3js.org/d3.v3.min.js to serve D3.

We should always use https so that this problem doesn't accidentally happen.
https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.js

Replacing the D3 script source should remove any errors whether its http or https.

Thanks for spotting this!
Alex

**Comment by hamoid** [comment]
Thanks! That must be it. Probably my HTTPS-Everywhere plugin :) Thanks
for the fix!
